In [ ]:
# Write your code here:
def add_item(cart, item_name, price, quantity): 
    # Your code here 
    if price <= 0 or quantity <= 0: 
        return False 
    if item_name in cart: 
        cart[item_name]['quantity'] += quantity 
    else: 
        cart[item_name] = {'price': price, 'quantity': quantity} 
    return True 

def calculate_total(cart): 
    if not cart: 
        return 0 
    return sum(item['price'] * item['quantity'] for item in cart.values()) 

def apply_discount(cart, discount_percent): 
    if not (0 <= discount_percent <= 100): 
        return False 
    for item in cart.values(): 
        item['price'] *= (1 - discount_percent / 100) 
    return True

# Test your functions
cart = {} 
# Test adding items 
print(add_item(cart, "Milk", 3.50, 2))      
print(add_item(cart, "Eggs", -1.00, 1))     
print(add_item(cart, "Bread", 2.00, 3))     
# Test total 
print(f"Total: ${calculate_total(cart):.2f}") 
# Test discount 
print(apply_discount(cart, 20))  # 20% off 
print(f"After discount: ${calculate_total(cart):.2f}") 

True
False
True
Total: $13.00
True
After discount: $10.40


In [ ]:
import numpy as np
 # Write your code here:
def create_score_array(num_students, num_exams): 
    return np.random.randint(60, 101, size=(num_students, num_exams)) 
def find_struggling_students(scores, threshold): 
    return np.mean(scores, axis=1) < threshold
def curve_scores(scores, points): 
    curved = scores + points
    return np.minimum(curved, 100)
def get_exam_statistics(scores): 
    stats = {}
    for i in range(scores.shape[1]):
        stats[f"exam_{i}"] = {
            "mean": np.mean(scores[:, i]),
            "max": np.max(scores[:, i]),
            "min": np.min(scores[:, i])
        }
    return stats
# Test your functions
# Create test scores 
scores = create_score_array(6, 4)  # 6 students, 4 exams 
print("Original scores:\n", scores) 
# Find struggling students (average < 75) 
struggling = find_struggling_students(scores, 75) 
print(f"\nStruggling students (avg < 75): {struggling}") 
# Curve scores by 5 points 
curved = curve_scores(scores, 5) 
print("\nCurved scores:\n", curved) 
# Get statistics 
stats = get_exam_statistics(scores) 
for exam, data in stats.items(): 
    print(f"{exam}: mean={data['mean']:.1f}, max={data['max']}, min={data['min']}")

Original scores:
 [[96 67 78 88]
 [90 67 97 70]
 [85 79 93 60]
 [85 87 86 69]
 [98 69 98 82]
 [68 98 68 67]]

Struggling students (avg < 75): [False False False False False False]

Curved scores:
 [[100  72  83  93]
 [ 95  72 100  75]
 [ 90  84  98  65]
 [ 90  92  91  74]
 [100  74 100  87]
 [ 73 100  73  72]]
exam_0: mean=87.0, max=98, min=68
exam_1: mean=77.8, max=98, min=67
exam_2: mean=86.7, max=98, min=68
exam_3: mean=72.7, max=88, min=60


In [ ]:
# Write your code here:
def add_student_to_club(clubs_dict, club_name, student_name): 
    if club_name not in clubs_dict:
        clubs_dict[club_name] = set()
    clubs_dict[club_name].add(student_name)

def get_students_in_multiple_clubs(clubs_dict): 
    student_club_count = {}
    for members in clubs_dict.values():
        for student in members:
            if student in student_club_count:
                student_club_count[student] += 1
            else:
                student_club_count[student] = 1
    return {student for student, count in student_club_count.items() if count >= 2} 

def find_exclusive_members(clubs_dict, club1_name, club2_name): 
    if club1_name not in clubs_dict or club2_name not in clubs_dict:
        return set()
    return clubs_dict[club1_name] - clubs_dict[club2_name]

# Bonus Question
def merge_clubs(clubs_dict, old_club, new_club):
    if old_club not in clubs_dict:
        return False
    if new_club not in clubs_dict:
        clubs_dict[new_club] = set()
    clubs_dict[new_club].update(clubs_dict[old_club])
    del clubs_dict[old_club]
    return True

# Test your functions
clubs = {} 
# Add students to clubs 
add_student_to_club(clubs, "Math", "Alice") 
add_student_to_club(clubs, "Math", "Bob") 
add_student_to_club(clubs, "Science", "Alice") 
add_student_to_club(clubs, "Science", "Charlie") 
add_student_to_club(clubs, "Art", "David") 
print("Clubs:", clubs) 
print("In multiple clubs:", get_students_in_multiple_clubs(clubs)) 
print("Math only:", find_exclusive_members(clubs, "Math", "Science"))
add_student_to_club(clubs, "Photography", "Eve") 
print(merge_clubs(clubs, "Photography", "Art")) 
print("After merge:", clubs)

Clubs: {'Math': {'Bob', 'Alice'}, 'Science': {'Charlie', 'Alice'}, 'Art': {'David'}}
In multiple clubs: {'Alice'}
Math only: {'Bob'}
True
After merge: {'Math': {'Bob', 'Alice'}, 'Science': {'Charlie', 'Alice'}, 'Art': {'David', 'Eve'}}
